### ISSUE TITLE
redhillonrails not compatible with newest mysql2?

### ISSUE THREAD

**Issue by raroni** [mlomnicki/redhillonrails_core#11]
Upgrading to newest mysql2 (0.2.7) breaks my application. If I remove redhillonrails_core it works again.

This is the error I see when trying to use mysql2 0.2.7 and redhillonrails_core. Using redhillonrails_core 1.1.3.

```
    ruby-1.9.2-p136 :001 > a = Airline.new
    NoMethodError: undefined method `case_sensitive?' for #<ActiveRecord::ConnectionAdapters::Mysql2IndexDefinition:0x00000100ef30c0>
        from /Users/rasmus/.rvm/gems/ruby-1.9.2-p136/gems/redhillonrails_core-1.1.3/lib/redhillonrails_core/active_record/base.rb:33:in `block in columns_with_redhillonrails_core'
        from /Users/rasmus/.rvm/gems/ruby-1.9.2-p136/gems/redhillonrails_core-1.1.3/lib/redhillonrails_core/active_record/base.rb:29:in `each'
        from /Users/rasmus/.rvm/gems/ruby-1.9.2-p136/gems/redhillonrails_core-1.1.3/lib/redhillonrails_core/active_record/base.rb:29:in `columns_with_redhillonrails_core'
        from /Users/rasmus/.rvm/gems/ruby-1.9.2-p136/gems/activerecord-3.0.5/lib/active_record/persistence.rb:284:in `attributes_from_column_definition'
        from /Users/rasmus/.rvm/gems/ruby-1.9.2-p136/gems/activerecord-3.0.5/lib/active_record/locking/optimistic.rb:62:in `attributes_from_column_definition'
        from /Users/rasmus/.rvm/gems/ruby-1.9.2-p136/gems/activerecord-3.0.5/lib/active_record/base.rb:1394:in `initialize'
        from (irb):1:in `new'
```

**Comment by gsusmonzon** [comment]
I just updated, and it is happening the same (this time RoR 3.05 + ree1.8.7):

It seems that worked with mysql2 0.2.6 gem BUT newest version (0.2.7) make this break

User.new  --> throws:

NoMethodError: undefined method `case_sensitive?' for #<ActiveRecord::ConnectionAdapters::Mysql2IndexDefinition:0x3837c20>
        from /opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/redhillonrails_core-1.1.3/lib/redhillonrails_core/active_record/base.rb:33:in`columns'
        from /opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/redhillonrails_core-1.1.3/lib/redhillonrails_core/active_record/base.rb:29:in `each'
        from /opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/redhillonrails_core-1.1.3/lib/redhillonrails_core/active_record/base.rb:29:in`columns'
        from /opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activerecord-3.0.5/lib/active_record/persistence.rb:284:in `attributes_from_column_definition'
        from /opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activerecord-3.0.5/lib/active_record/locking/optimistic.rb:62:in`attributes_from_column_definition'
        from /opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/activerecord-3.0.5/lib/active_record/base.rb:1394:in `initialize'

**Comment by raroni** [comment]
This commit in mysql2 seems to be the culprit:

https://github.com/brianmario/mysql2/commit/90ddb63e52cd48c1a1b46acb41cb66552a781f34

Mysql2 now uses it's own Mysql2IndexDefinition instead of ActiveRecord's IndexDefinition it seems.

I've made this quick'n dirty rails initializer that fixes the problem:

```
module ActiveRecord
  module ConnectionAdapters
    class Mysql2IndexDefinition
      attr_accessor :conditions, :expression, :kind

      def case_sensitive?
        @case_sensitive.nil? ? true : @case_sensitive
      end

      def case_sensitive=(case_sensitive)
        @case_sensitive = case_sensitive
      end
    end
  end
end
```

Indeed not very nice, but it works for now. I wish the author of redhillonrails_core, @mlomnicki, would share his thoughts on this issue.

**Comment by juanmaflyer** [comment]
I am facing the same error with mysql2 (0.2.11) and the error is exactly the same as the one described in the comments above. I've tested @rasmusrn suggestion and it worked but I think the gem could be updated in order to work with newest mysql2 gem versions.

**Comment by kastman** [comment]
I just came across this a day after juan did (mysql2 0.2.11 as well), and second everything above. Thanks to @rasmusrn for the initializer hack. It would be nice to have an update, but it sounds like these redhill plugins really aren't supported anymore, although clearly they're still being used. Oh well; working is working, hack or no.

**Comment by mlomnicki** [comment]
Hi everyone!

  The issue mentioned here is now fixed in master branch. Thanks for your patience :)
I'm going to release 1.2.0 version within few days if everything is OK.

There is also rails31 branch which aims to provide compatibility with rails 3.1.0 and mysql 0.3.X. On my box all tests are green at the moment.

@kastman redhillonrails_core is supported and I have no plans to drop it. I have much more spare time now so expect bugfixes within days not within months ;)

I have also created google group. Please subscribe and ask questions there. http://groups.google.com/group/rails-db

Cheers,
Michał

**Comment by mlomnicki** [comment]
No issues were reported so I've just released redhillonrails_core 1.2.0 on rubygems.

**Comment by juanmaflyer** [comment]
Thanks!!! :D

**Comment by gsusmonzon** [comment]
Thanks

**Comment by raroni** [comment]
Thanks @mlomnicki - it's nice to get rid of my ugly hack :)
